# Generated by Django 4.2 on 2023-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
